# Generated by Django 6.0.5 on 2026-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_reportexport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentactivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("status_changed", "Status Changed"),
                    ("priority_changed", "Priority Changed"),
                    ("assigned", "Assigned"),
                    ("commented", "Commented"),
                    ("attachment_uploaded", "Attachment Uploaded"),
                    ("attachment_deleted", "Attachment Deleted"),
                    ("returned", "Returned"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                    ("comment_deleted", "Comment Deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
